# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Marco Milanta
title: Master student at ETHz
email: mmilanta@ethz.ch
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  mmilanta
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: marco-milanta
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/caplena-marco-milanta-0676-media-.JPG
about_content: | # this will include new lines to allow paragraphs
  Creative and passionate Machine Learning Engineer. Confortable with <mark>mathematics</mark> and <mark>programming</mark>. He is eager to focus on hard problems working well in a team.
content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#        description: | # this will include new lines to allow paragraphs
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NLP Research Engineer
        link: caplena.com
        # link_text: boringcompany.com
        caption: Spring 2023
        #quote: >
        description: | # this will include new lines to allow paragraphs
            Working on an NLP startup focusing on sentiment analysis. First hand experience with large lenguage models. 
      - layout: left
        title: Research Assistant
        link: ethz.ch
        # link_text: boringcompany.com
        caption: Spring 2022
        #quote: >
        description: | # this will include new lines to allow paragraphs
            I am working to complete a project that uses deep learning techniques to forecast the effect of droughts 🌎.
      - layout: left
        title: Teaching Assistant
        link: ethz.ch
        # link_text: boringcompany.com
        caption: Autumn 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
            I have worked as a TA for [Probabilistic Artificial Intelligence](https://las.inf.ethz.ch/teaching/pai-f21), a class by Andreas Krause at ETHz. I held some tutorials and worked behind the scenes to prepare homework and slides.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Politecnico di Milano
        caption: 2017 - 2020
        sub_title: Bachelor in Mathematical Engineering
        description: | # this will include new lines to allow paragraphs
          At Polimi I got in touch with the beautiful world of mathematics. I learned a lot of theorems from all over mathematics, but, even more important, I learned how to come up with extensive and original proofs. I also learned how to apply all of this knowledge in practical problems: from applied statistics to PDE's numerical calculus.
      - layout: left
        title: ETHz
        caption: 2020 - 2022
        sub_title: Master in Data Science
        description: | # this will include new lines to allow paragraphs
          In this master, I dived into the world of machine learning. Starting from theory, all the way to real-world implementations.
  
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Strong inductive biases provably prevent harmless interpolation
        caption: Published at ICLR 2023
        description: | # this will include new lines to allow paragraphs
          Counterintutivly, many very large models perform well even when they interpolate the training data. However, there are still many exceptions in which this phenomenon fails. We investigates how inductive bias plays a crucial role. Paper available [here](https://arxiv.org/abs/2301.07605).
      - layout: left
        title: Deep learning for satellite image forecasting of vegetation greenness
        caption: In review at Environmental Data Science, Cambridge 
        description: | # this will include new lines to allow paragraphs
          We worked on a deep learning model to forecast how satellite images in a fixed location evolve through time, conditioned on weather data. We implemented a convolutional version of s LSTM network to encode prior knowladge of both temporal and spatial dependencies. The preprint is can be found [here](https://www.biorxiv.org/content/10.1101/2022.08.16.504173), code is available in [this repo](github.com/rudolfwilliam/satellite_image_forecasting).
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mathematics and machine learning, some of my other interests and hobbies are:
      - Rock climbing
      - Cooking ([Here](https://mmilanta.github.io/le_ricette_di_nonna_aua/) a website with my Grandma's recipes, but they are all in Italian)
      - Going on holidays

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
